FAMILY_KIND__ANY = 0
FAMILY_KIND__NO_FIT = 1
FAMILY_KIND__LATIN_TEXT = 2
FAMILY_KIND__LATIN_HANDWRITTEN = 3
FAMILY_KIND__LATIN_DECORATIVE = 4
FAMILY_KIND__LATIN_SYMBOL = 5

FIELD__FAMILY_KIND = 0

FIELD__LATIN_TEXT__FAMILY_KIND = 0
FIELD__LATIN_TEXT__SERIF_STYLE = 1
FIELD__LATIN_TEXT__WEIGHT = 2
FIELD__LATIN_TEXT__PROPORTION = 3
FIELD__LATIN_TEXT__CONTRAST = 4
FIELD__LATIN_TEXT__STROKE_VARIATION = 5
FIELD__LATIN_TEXT__ARM_STYLE = 6
FIELD__LATIN_TEXT__LETTERFORM = 7
FIELD__LATIN_TEXT__MIDLINE = 8
FIELD__LATIN_TEXT__X_HEIGHT = 9

LATIN_TEXT__SERIF_STYLE__ANY = 0
LATIN_TEXT__SERIF_STYLE__NO_FIT = 1
LATIN_TEXT__SERIF_STYLE__COVE = 2
LATIN_TEXT__SERIF_STYLE__OBTUSE_COVE = 3
LATIN_TEXT__SERIF_STYLE__SQUARE_COVE = 4
LATIN_TEXT__SERIF_STYLE__OBTUSE_SQUARE_COVE = 5
LATIN_TEXT__SERIF_STYLE__SQUARE = 6
LATIN_TEXT__SERIF_STYLE__THIN = 7
LATIN_TEXT__SERIF_STYLE__OVAL = 8
LATIN_TEXT__SERIF_STYLE__EXAGGERATED = 9
LATIN_TEXT__SERIF_STYLE__TRIANGLE = 10
LATIN_TEXT__SERIF_STYLE__NORMAL_SANS = 11
LATIN_TEXT__SERIF_STYLE__OBTUSE_SANS = 12
LATIN_TEXT__SERIF_STYLE__PERPENDICULAR_SANS = 13

LATIN_TEXT__WEIGHT__ANY = 0
LATIN_TEXT__WEIGHT__NO_FIT = 1
LATIN_TEXT__WEIGHT__VERY_LIGHT = 2
LATIN_TEXT__WEIGHT__LIGHT = 3
LATIN_TEXT__WEIGHT__THIN = 4
LATIN_TEXT__WEIGHT__BOOK = 5
LATIN_TEXT__WEIGHT__MEDIUM = 6
LATIN_TEXT__WEIGHT__DEMI = 7
LATIN_TEXT__WEIGHT__BOLD = 8
LATIN_TEXT__WEIGHT__HEAVY = 9
LATIN_TEXT__WEIGHT__BLACK = 10
LATIN_TEXT__WEIGHT__EXTRA_BLACK = 11

LATIN_TEXT__PROPORTION__ANY = 0
LATIN_TEXT__PROPORTION__NO_FIT = 1
LATIN_TEXT__PROPORTION__OLD_STYLE = 2
LATIN_TEXT__PROPORTION__MODERN = 3
LATIN_TEXT__PROPORTION__EVEN_WIDTH = 4
LATIN_TEXT__PROPORTION__EXTENDED = 5
LATIN_TEXT__PROPORTION__CONDENSED = 6
LATIN_TEXT__PROPORTION__VERY_EXTENDED = 7
LATIN_TEXT__PROPORTION__VERY_CONDENSED = 8
LATIN_TEXT__PROPORTION__MONOSPACED = 9

LATIN_TEXT__CONTRAST__ANY = 0
LATIN_TEXT__CONTRAST__NO_FIT = 1
LATIN_TEXT__CONTRAST__NONE = 2
LATIN_TEXT__CONTRAST__VERY_LOW = 3
LATIN_TEXT__CONTRAST__LOW = 4
LATIN_TEXT__CONTRAST__MEDIUM_LOW = 5
LATIN_TEXT__CONTRAST__MEDIUM = 6
LATIN_TEXT__CONTRAST__MEDIUM_HIGH = 7
LATIN_TEXT__CONTRAST__HIGH = 8
LATIN_TEXT__CONTRAST__VERY_HIGH = 9

LATIN_TEXT__STROKE_VARIATION__ANY = 0
LATIN_TEXT__STROKE_VARIATION__NO_FIT = 1
LATIN_TEXT__STROKE_VARIATION__NO_VARIATION = 2
LATIN_TEXT__STROKE_VARIATION__GRADUAL_DIAGONAL = 3
LATIN_TEXT__STROKE_VARIATION__GRADUAL_TRANSITIONAL = 4
LATIN_TEXT__STROKE_VARIATION__GRADUAL_VERTICAL = 5
LATIN_TEXT__STROKE_VARIATION__GRADUAL_HORIZONTAL = 6
LATIN_TEXT__STROKE_VARIATION__RAPID_VERTICAL = 7
LATIN_TEXT__STROKE_VARIATION__RAPID_HORIZONTAL = 8
LATIN_TEXT__STROKE_VARIATION__INSTANT_VERTICAL = 9
LATIN_TEXT__STROKE_VARIATION__INSTANT_HORIZONTAL = 10

LATIN_TEXT__ARM_STYLE__ANY = 0
LATIN_TEXT__ARM_STYLE__NO_FIT = 1
LATIN_TEXT__ARM_STYLE__STRAIGHT_ARMS_HORIZONTAL = 2
LATIN_TEXT__ARM_STYLE__STRAIGHT_ARMS_WEDGE = 3
LATIN_TEXT__ARM_STYLE__STRAIGHT_ARMS_VERTICAL = 4
LATIN_TEXT__ARM_STYLE__STRAIGHT_ARMS_SINGLE_SERIF = 5
LATIN_TEXT__ARM_STYLE__STRAIGHT_ARMS_DOUBLE_SERIF = 6
LATIN_TEXT__ARM_STYLE__NON_STRAIGHT_HORIZONTAL = 7
LATIN_TEXT__ARM_STYLE__NON_STRAIGHT_WEDGE = 8
LATIN_TEXT__ARM_STYLE__NON_STRAIGHT_VERTICAL = 9
LATIN_TEXT__ARM_STYLE__NON_STRAIGHT_SINGLE_SERIF = 10
LATIN_TEXT__ARM_STYLE__NON_STRAIGHT_DOUBLE_SERIF = 11

LATIN_TEXT__LETTERFORM__ANY = 0
LATIN_TEXT__LETTERFORM__NO_FIT = 1
LATIN_TEXT__LETTERFORM__NORMAL_CONTACT = 2
LATIN_TEXT__LETTERFORM__NORMAL_WEIGHTED = 3
LATIN_TEXT__LETTERFORM__NORMAL_BOXED = 4
LATIN_TEXT__LETTERFORM__NORMAL_FLATTENED = 5
LATIN_TEXT__LETTERFORM__NORMAL_ROUNDED = 6
LATIN_TEXT__LETTERFORM__NORMAL_OFF_CENTER = 7
LATIN_TEXT__LETTERFORM__NORMAL_SQUARE = 8
LATIN_TEXT__LETTERFORM__OBLIQUE_CONTACT = 9
LATIN_TEXT__LETTERFORM__OBLIQUE_WEIGHTED = 10
LATIN_TEXT__LETTERFORM__OBLIQUE_BOXED = 11
LATIN_TEXT__LETTERFORM__OBLIQUE_FLATTENED = 12
LATIN_TEXT__LETTERFORM__OBLIQUE_ROUNDED = 13
LATIN_TEXT__LETTERFORM__OBLIQUE_OFF_CENTER = 14
LATIN_TEXT__LETTERFORM__OBLIQUE_SQUARE = 15

LATIN_TEXT__MIDLINE__ANY = 0
LATIN_TEXT__MIDLINE__NO_FIT = 1
LATIN_TEXT__MIDLINE__STANDARD_TRIMMED = 2
LATIN_TEXT__MIDLINE__STANDARD_POINTED = 3
LATIN_TEXT__MIDLINE__STANDARD_SERIFED = 4
LATIN_TEXT__MIDLINE__HIGH_TRIMMED = 5
LATIN_TEXT__MIDLINE__HIGH_POINTED = 6
LATIN_TEXT__MIDLINE__HIGH_SERIFED = 7
LATIN_TEXT__MIDLINE__CONSTANT_TRIMMED = 8
LATIN_TEXT__MIDLINE__CONSTANT_POINTED = 9
LATIN_TEXT__MIDLINE__CONSTANT_SERIFED = 10
LATIN_TEXT__MIDLINE__LOW_TRIMMED = 11
LATIN_TEXT__MIDLINE__LOW_POINTED = 12
LATIN_TEXT__MIDLINE__LOW_SERIFED = 13

LATIN_TEXT__X_HEIGHT__ANY = 0
LATIN_TEXT__X_HEIGHT__NO_FIT = 1
LATIN_TEXT__X_HEIGHT__CONSTANT_SMALL = 2
LATIN_TEXT__X_HEIGHT__CONSTANT_STANDARD = 3
LATIN_TEXT__X_HEIGHT__CONSTANT_LARGE = 4
LATIN_TEXT__X_HEIGHT__DUCKING_SMALL = 5
LATIN_TEXT__X_HEIGHT__DUCKING_STANDARD = 6
LATIN_TEXT__X_HEIGHT__DUCKING_LARGE = 7

FIELD__LATIN_HANDWRITTEN__FAMILY_KIND = 0
FIELD__LATIN_HANDWRITTEN__TOOL_KIND = 1
FIELD__LATIN_HANDWRITTEN__WEIGHT = 2
FIELD__LATIN_HANDWRITTEN__SPACING = 3
FIELD__LATIN_HANDWRITTEN__ASPECT_RATIO = 4
FIELD__LATIN_HANDWRITTEN__CONTRAST = 5
FIELD__LATIN_HANDWRITTEN__TOPOLOGY = 6
FIELD__LATIN_HANDWRITTEN__FORM = 7
FIELD__LATIN_HANDWRITTEN__FINIALS = 8
FIELD__LATIN_HANDWRITTEN__X_ASCENT = 9

LATIN_HANDWRITTEN__TOOL_KIND__ANY = 0
LATIN_HANDWRITTEN__TOOL_KIND__NO_FIT = 1
LATIN_HANDWRITTEN__TOOL_KIND__FLAT_NIB = 2
LATIN_HANDWRITTEN__TOOL_KIND__PRESSURE_POINT = 3
LATIN_HANDWRITTEN__TOOL_KIND__ENGRAVED = 4
LATIN_HANDWRITTEN__TOOL_KIND__BALL_ROUND_CAP = 5
LATIN_HANDWRITTEN__TOOL_KIND__BRUSH = 6
LATIN_HANDWRITTEN__TOOL_KIND__ROUGH = 7
LATIN_HANDWRITTEN__TOOL_KIND__FELT_PEN_BRUSH_TIP = 8
LATIN_HANDWRITTEN__TOOL_KIND__WILD_BRUSH_DRIPS_A_LOT = 9

LATIN_HANDWRITTEN__WEIGHT__ANY = 0
LATIN_HANDWRITTEN__WEIGHT__NO_FIT = 1
LATIN_HANDWRITTEN__WEIGHT__VERY_LIGHT = 2
LATIN_HANDWRITTEN__WEIGHT__LIGHT = 3
LATIN_HANDWRITTEN__WEIGHT__THIN = 4
LATIN_HANDWRITTEN__WEIGHT__BOOK = 5
LATIN_HANDWRITTEN__WEIGHT__MEDIUM = 6
LATIN_HANDWRITTEN__WEIGHT__DEMI = 7
LATIN_HANDWRITTEN__WEIGHT__BOLD = 8
LATIN_HANDWRITTEN__WEIGHT__HEAVY = 9
LATIN_HANDWRITTEN__WEIGHT__BLACK = 10
LATIN_HANDWRITTEN__WEIGHT__EXTRA_BLACK_NORD = 11

LATIN_HANDWRITTEN__SPACING__ANY = 0
LATIN_HANDWRITTEN__SPACING__NO_FIT = 1
LATIN_HANDWRITTEN__SPACING__PROPORTIONAL_SPACED = 2
LATIN_HANDWRITTEN__SPACING__MONOSPACED = 3

LATIN_HANDWRITTEN__ASPECT_RATIO__ANY = 0
LATIN_HANDWRITTEN__ASPECT_RATIO__NO_FIT = 1
LATIN_HANDWRITTEN__ASPECT_RATIO__VERY_CONDENSED = 2
LATIN_HANDWRITTEN__ASPECT_RATIO__CONDENSED = 3
LATIN_HANDWRITTEN__ASPECT_RATIO__NORMAL = 4
LATIN_HANDWRITTEN__ASPECT_RATIO__EXPANDED = 5
LATIN_HANDWRITTEN__ASPECT_RATIO__VERY_EXPANDED = 6

LATIN_HANDWRITTEN__CONTRAST__ANY = 0
LATIN_HANDWRITTEN__CONTRAST__NO_FIT = 1
LATIN_HANDWRITTEN__CONTRAST__NONE = 2
LATIN_HANDWRITTEN__CONTRAST__VERY_LOW = 3
LATIN_HANDWRITTEN__CONTRAST__LOW = 4
LATIN_HANDWRITTEN__CONTRAST__MEDIUM_LOW = 5
LATIN_HANDWRITTEN__CONTRAST__MEDIUM = 6
LATIN_HANDWRITTEN__CONTRAST__MEDIUM_HIGH = 7
LATIN_HANDWRITTEN__CONTRAST__HIGH = 8
LATIN_HANDWRITTEN__CONTRAST__VERY_HIGH = 9

LATIN_HANDWRITTEN__TOPOLOGY__ANY = 0
LATIN_HANDWRITTEN__TOPOLOGY__NO_FIT = 1
LATIN_HANDWRITTEN__TOPOLOGY__ROMAN_DISCONNECTED = 2
LATIN_HANDWRITTEN__TOPOLOGY__ROMAN_TRAILING = 3
LATIN_HANDWRITTEN__TOPOLOGY__ROMAN_CONNECTED = 4
LATIN_HANDWRITTEN__TOPOLOGY__CURSIVE_DISCONNECTED = 5
LATIN_HANDWRITTEN__TOPOLOGY__CURSIVE_TRAILING = 6
LATIN_HANDWRITTEN__TOPOLOGY__CURSIVE_CONNECTED = 7
LATIN_HANDWRITTEN__TOPOLOGY__BLACKLETTER_DISCONNECTED = 8
LATIN_HANDWRITTEN__TOPOLOGY__BLACKLETTER_TRAILING = 9
LATIN_HANDWRITTEN__TOPOLOGY__BLACKLETTER_CONNECTED = 10

LATIN_HANDWRITTEN__FORM__ANY = 0
LATIN_HANDWRITTEN__FORM__NO_FIT = 1
LATIN_HANDWRITTEN__FORM__UPRIGHT_NO_WRAPPING = 2
LATIN_HANDWRITTEN__FORM__UPRIGHT_SOME_WRAPPING = 3
LATIN_HANDWRITTEN__FORM__UPRIGHT_MORE_WRAPPING = 4
LATIN_HANDWRITTEN__FORM__UPRIGHT_EXTREME_WRAPPING = 5
LATIN_HANDWRITTEN__FORM__OBLIQUE_NO_WRAPPING = 6
LATIN_HANDWRITTEN__FORM__OBLIQUE_SOME_WRAPPING = 7
LATIN_HANDWRITTEN__FORM__OBLIQUE_MORE_WRAPPING = 8
LATIN_HANDWRITTEN__FORM__OBLIQUE_EXTREME_WRAPPING = 9
LATIN_HANDWRITTEN__FORM__EXAGGERATED_NO_WRAPPING = 10
LATIN_HANDWRITTEN__FORM__EXAGGERATED_SOME_WRAPPING = 11
LATIN_HANDWRITTEN__FORM__EXAGGERATED_MORE_WRAPPING = 12
LATIN_HANDWRITTEN__FORM__EXAGGERATED_EXTREME_WRAPPING = 13

LATIN_HANDWRITTEN__FINIALS__ANY = 0
LATIN_HANDWRITTEN__FINIALS__NO_FIT = 1
LATIN_HANDWRITTEN__FINIALS__NONE_NO_LOOPS = 2
LATIN_HANDWRITTEN__FINIALS__NONE_CLOSED_LOOPS = 3
LATIN_HANDWRITTEN__FINIALS__NONE_OPEN_LOOPS = 4
LATIN_HANDWRITTEN__FINIALS__SHARP_NO_LOOPS = 5
LATIN_HANDWRITTEN__FINIALS__SHARP_CLOSED_LOOPS = 6
LATIN_HANDWRITTEN__FINIALS__SHARP_OPEN_LOOPS = 7
LATIN_HANDWRITTEN__FINIALS__TAPERED_NO_LOOPS = 8
LATIN_HANDWRITTEN__FINIALS__TAPERED_CLOSED_LOOPS = 9
LATIN_HANDWRITTEN__FINIALS__TAPERED_OPEN_LOOPS = 10

LATIN_HANDWRITTEN__X_ASCENT__ANY = 0
LATIN_HANDWRITTEN__X_ASCENT__NO_FIT = 1
LATIN_HANDWRITTEN__X_ASCENT__VERY_LOW = 2
LATIN_HANDWRITTEN__X_ASCENT__LOW = 3
LATIN_HANDWRITTEN__X_ASCENT__MEDIUM = 4
LATIN_HANDWRITTEN__X_ASCENT__HIGH = 5
LATIN_HANDWRITTEN__X_ASCENT__VERY_HIGH = 6

FIELD__LATIN_DECORATIVE__FAMILY_KIND = 0
FIELD__LATIN_DECORATIVE__CLASS = 1
FIELD__LATIN_DECORATIVE__WEIGHT = 2
FIELD__LATIN_DECORATIVE__ASPECT = 3
FIELD__LATIN_DECORATIVE__CONTRAST = 4
FIELD__LATIN_DECORATIVE__SERIF_VARIANT = 5
FIELD__LATIN_DECORATIVE__TREATMENT = 6
FIELD__LATIN_DECORATIVE__LINING = 7
FIELD__LATIN_DECORATIVE__TOPOLOGY = 8
FIELD__LATIN_DECORATIVE__RANGE_OF_CHARACTERS = 9

LATIN_DECORATIVE__CLASS__ANY = 0
LATIN_DECORATIVE__CLASS__NO_FIT = 1
LATIN_DECORATIVE__CLASS__DERIVATIVE = 2
LATIN_DECORATIVE__CLASS__NON_STANDARD_TOPOLOGY = 3
LATIN_DECORATIVE__CLASS__NON_STANDARD_ELEMENTS = 4
LATIN_DECORATIVE__CLASS__NON_STANDARD_ASPECT = 5
LATIN_DECORATIVE__CLASS__INITIALS = 6
LATIN_DECORATIVE__CLASS__CARTOON = 7
LATIN_DECORATIVE__CLASS__PICTURE_STEMS = 8
LATIN_DECORATIVE__CLASS__ORNAMENTED = 9
LATIN_DECORATIVE__CLASS__TEXT_AND_BACKGROUND = 10
LATIN_DECORATIVE__CLASS__COLLAGE = 11
LATIN_DECORATIVE__CLASS__MONTAGE = 12

LATIN_DECORATIVE__WEIGHT__ANY = 0
LATIN_DECORATIVE__WEIGHT__NO_FIT = 1
LATIN_DECORATIVE__WEIGHT__VERY_LIGHT = 2
LATIN_DECORATIVE__WEIGHT__LIGHT = 3
LATIN_DECORATIVE__WEIGHT__THIN = 4
LATIN_DECORATIVE__WEIGHT__BOOK = 5
LATIN_DECORATIVE__WEIGHT__MEDIUM = 6
LATIN_DECORATIVE__WEIGHT__DEMI = 7
LATIN_DECORATIVE__WEIGHT__BOLD = 8
LATIN_DECORATIVE__WEIGHT__HEAVY = 9
LATIN_DECORATIVE__WEIGHT__BLACK = 10
LATIN_DECORATIVE__WEIGHT__EXTRA_BLACK = 11

LATIN_DECORATIVE__ASPECT__ANY = 0
LATIN_DECORATIVE__ASPECT__NO_FIT = 1
LATIN_DECORATIVE__ASPECT__SUPER_CONDENSED = 2
LATIN_DECORATIVE__ASPECT__VERY_CONDENSED = 3
LATIN_DECORATIVE__ASPECT__CONDENSED = 4
LATIN_DECORATIVE__ASPECT__NORMAL = 5
LATIN_DECORATIVE__ASPECT__EXTENDED = 6
LATIN_DECORATIVE__ASPECT__VERY_EXTENDED = 7
LATIN_DECORATIVE__ASPECT__SUPER_EXTENDED = 8
LATIN_DECORATIVE__ASPECT__MONOSPACED = 9

LATIN_DECORATIVE__CONTRAST__ANY = 0
LATIN_DECORATIVE__CONTRAST__NO_FIT = 1
LATIN_DECORATIVE__CONTRAST__NONE = 2
LATIN_DECORATIVE__CONTRAST__VERY_LOW = 3
LATIN_DECORATIVE__CONTRAST__LOW = 4
LATIN_DECORATIVE__CONTRAST__MEDIUM_LOW = 5
LATIN_DECORATIVE__CONTRAST__MEDIUM = 6
LATIN_DECORATIVE__CONTRAST__MEDIUM_HIGH = 7
LATIN_DECORATIVE__CONTRAST__HIGH = 8
LATIN_DECORATIVE__CONTRAST__VERY_HIGH = 9
LATIN_DECORATIVE__CONTRAST__HORIZONTAL_LOW = 10
LATIN_DECORATIVE__CONTRAST__HORIZONTAL_MEDIUM = 11
LATIN_DECORATIVE__CONTRAST__HORIZONTAL_HIGH = 12
LATIN_DECORATIVE__CONTRAST__BROKEN = 13

LATIN_DECORATIVE__SERIF_VARIANT__ANY = 0
LATIN_DECORATIVE__SERIF_VARIANT__NO_FIT = 1
LATIN_DECORATIVE__SERIF_VARIANT__COVE = 2
LATIN_DECORATIVE__SERIF_VARIANT__OBTUSE_COVE = 3
LATIN_DECORATIVE__SERIF_VARIANT__SQUARE_COVE = 4
LATIN_DECORATIVE__SERIF_VARIANT__OBTUSE_SQUARE_COVE = 5
LATIN_DECORATIVE__SERIF_VARIANT__SQUARE = 6
LATIN_DECORATIVE__SERIF_VARIANT__THIN = 7
LATIN_DECORATIVE__SERIF_VARIANT__OVAL = 8
LATIN_DECORATIVE__SERIF_VARIANT__EXAGGERATED = 9
LATIN_DECORATIVE__SERIF_VARIANT__TRIANGLE = 10
LATIN_DECORATIVE__SERIF_VARIANT__NORMAL_SANS = 11
LATIN_DECORATIVE__SERIF_VARIANT__OBTUSE_SANS = 12
LATIN_DECORATIVE__SERIF_VARIANT__PERPENDICULAR_SANS = 13
LATIN_DECORATIVE__SERIF_VARIANT__FLARED = 14
LATIN_DECORATIVE__SERIF_VARIANT__ROUNDED = 15
LATIN_DECORATIVE__SERIF_VARIANT__SCRIPT = 16

LATIN_DECORATIVE__TREATMENT__ANY = 0
LATIN_DECORATIVE__TREATMENT__NO_FIT = 1
LATIN_DECORATIVE__TREATMENT__NONE_STANDARD_SOLID_FILL = 2
LATIN_DECORATIVE__TREATMENT__WHITE_NO_FILL = 3
LATIN_DECORATIVE__TREATMENT__PATTERNED_FILL = 4
LATIN_DECORATIVE__TREATMENT__COMPLEX_FILL = 5
LATIN_DECORATIVE__TREATMENT__SHAPED_FILL = 6
LATIN_DECORATIVE__TREATMENT__DRAWN_DISTRESSED = 7

LATIN_DECORATIVE__LINING__ANY = 0
LATIN_DECORATIVE__LINING__NO_FIT = 1
LATIN_DECORATIVE__LINING__NONE = 2
LATIN_DECORATIVE__LINING__INLINE = 3
LATIN_DECORATIVE__LINING__OUTLINE = 4
LATIN_DECORATIVE__LINING__ENGRAVED_MULTIPLE_LINES = 5
LATIN_DECORATIVE__LINING__SHADOW = 6
LATIN_DECORATIVE__LINING__RELIEF = 7
LATIN_DECORATIVE__LINING__BACKDROP = 8

LATIN_DECORATIVE__TOPOLOGY__ANY = 0
LATIN_DECORATIVE__TOPOLOGY__NO_FIT = 1
LATIN_DECORATIVE__TOPOLOGY__STANDARD = 2
LATIN_DECORATIVE__TOPOLOGY__SQUARE = 3
LATIN_DECORATIVE__TOPOLOGY__MULTIPLE_SEGMENT = 4
LATIN_DECORATIVE__TOPOLOGY__DECO_E_M_S_WACO_MIDLINES = 5
LATIN_DECORATIVE__TOPOLOGY__UNEVEN_WEIGHTING = 6
LATIN_DECORATIVE__TOPOLOGY__DIVERSE_ARMS = 7
LATIN_DECORATIVE__TOPOLOGY__DIVERSE_FORMS = 8
LATIN_DECORATIVE__TOPOLOGY__LOMBARDIC_FORMS = 9
LATIN_DECORATIVE__TOPOLOGY__UPPER_CASE_IN_LOWER_CASE = 10
LATIN_DECORATIVE__TOPOLOGY__IMPLIED_TOPOLOGY = 11
LATIN_DECORATIVE__TOPOLOGY__HORSESHOE_E_AND_A = 12
LATIN_DECORATIVE__TOPOLOGY__CURSIVE = 13
LATIN_DECORATIVE__TOPOLOGY__BLACKLETTER = 14
LATIN_DECORATIVE__TOPOLOGY__SWASH_VARIANCE = 15

LATIN_DECORATIVE__RANGE_OF_CHARACTERS__ANY = 0
LATIN_DECORATIVE__RANGE_OF_CHARACTERS__NO_FIT = 1
LATIN_DECORATIVE__RANGE_OF_CHARACTERS__EXTENDED_COLLECTION = 2
LATIN_DECORATIVE__RANGE_OF_CHARACTERS__LITTERALS = 3
LATIN_DECORATIVE__RANGE_OF_CHARACTERS__NO_LOWER_CASE = 4
LATIN_DECORATIVE__RANGE_OF_CHARACTERS__SMALL_CAPS = 5

FIELD__LATIN_SYMBOL__FAMILY_KIND = 0
FIELD__LATIN_SYMBOL__KIND = 1
FIELD__LATIN_SYMBOL__WEIGHT = 2
FIELD__LATIN_SYMBOL__SPACING = 3
FIELD__LATIN_SYMBOL__ASPECT_RATIO_CONTRAST = 4
FIELD__LATIN_SYMBOL__ASPECT_RATIO_CHAR_94 = 5
FIELD__LATIN_SYMBOL__ASPECT_RATIO_CHAR_119 = 6
FIELD__LATIN_SYMBOL__ASPECT_RATIO_CHAR_157 = 7
FIELD__LATIN_SYMBOL__ASPECT_RATIO_CHAR_163 = 8
FIELD__LATIN_SYMBOL__ASPECT_RATIO_CHAR_211 = 9

LATIN_SYMBOL__KIND__ANY = 0
LATIN_SYMBOL__KIND__NO_FIT = 1
LATIN_SYMBOL__KIND__MONTAGES = 2
LATIN_SYMBOL__KIND__PICTURES = 3
LATIN_SYMBOL__KIND__SHAPES = 4
LATIN_SYMBOL__KIND__SCIENTIFIC = 5
LATIN_SYMBOL__KIND__MUSIC = 6
LATIN_SYMBOL__KIND__EXPERT = 7
LATIN_SYMBOL__KIND__PATTERNS = 8
LATIN_SYMBOL__KIND__BOARDERS = 9
LATIN_SYMBOL__KIND__ICONS = 10
LATIN_SYMBOL__KIND__LOGOS = 11
LATIN_SYMBOL__KIND__INDUSTRY_SPECIFIC = 12

LATIN_SYMBOL__WEIGHT__NO_FIT = 1

LATIN_SYMBOL__SPACING__ANY = 0
LATIN_SYMBOL__SPACING__NO_FIT = 1
LATIN_SYMBOL__SPACING__PROPORTIONAL_SPACED = 2
LATIN_SYMBOL__SPACING__MONOSPACED = 3

LATIN_SYMBOL__ASPECT_RATIO_CONTRAST__NO_FIT = 1

LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__ANY = 0
LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__NO_FIT = 1
LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__NO_WIDTH = 2
LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__EXCEPTIONALLY_WIDE = 3
LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__SUPER_WIDE = 4
LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__VERY_WIDE = 5
LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__WIDE = 6
LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__NORMAL = 7
LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__NARROW = 8
LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__VERY_NARROW = 9

LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__ANY = 0
LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__NO_FIT = 1
LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__NO_WIDTH = 2
LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__EXCEPTIONALLY_WIDE = 3
LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__SUPER_WIDE = 4
LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__VERY_WIDE = 5
LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__WIDE = 6
LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__NORMAL = 7
LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__NARROW = 8
LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__VERY_NARROW = 9

LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__ANY = 0
LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__NO_FIT = 1
LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__NO_WIDTH = 2
LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__EXCEPTIONALLY_WIDE = 3
LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__SUPER_WIDE = 4
LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__VERY_WIDE = 5
LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__WIDE = 6
LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__NORMAL = 7
LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__NARROW = 8
LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__VERY_NARROW = 9

LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__ANY = 0
LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__NO_FIT = 1
LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__NO_WIDTH = 2
LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__EXCEPTIONALLY_WIDE = 3
LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__SUPER_WIDE = 4
LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__VERY_WIDE = 5
LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__WIDE = 6
LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__NORMAL = 7
LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__NARROW = 8
LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__VERY_NARROW = 9

LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__ANY = 0
LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__NO_FIT = 1
LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__NO_WIDTH = 2
LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__EXCEPTIONALLY_WIDE = 3
LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__SUPER_WIDE = 4
LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__VERY_WIDE = 5
LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__WIDE = 6
LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__NORMAL = 7
LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__NARROW = 8
LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__VERY_NARROW = 9


__all__ = [
    "FAMILY_KIND__ANY",
    "FAMILY_KIND__NO_FIT",
    "FAMILY_KIND__LATIN_TEXT",
    "FAMILY_KIND__LATIN_HANDWRITTEN",
    "FAMILY_KIND__LATIN_DECORATIVE",
    "FAMILY_KIND__LATIN_SYMBOL",
    "LATIN_TEXT__FAMILY_KIND",
    "LATIN_TEXT__SERIF_STYLE",
    "LATIN_TEXT__WEIGHT",
    "LATIN_TEXT__PROPORTION",
    "LATIN_TEXT__CONTRAST",
    "LATIN_TEXT__STROKE_VARIATION",
    "LATIN_TEXT__ARM_STYLE",
    "LATIN_TEXT__LETTERFORM",
    "LATIN_TEXT__MIDLINE",
    "LATIN_TEXT__X_HEIGHT",
    "LATIN_TEXT__SERIF_STYLE__ANY",
    "LATIN_TEXT__SERIF_STYLE__NO_FIT",
    "LATIN_TEXT__SERIF_STYLE__COVE",
    "LATIN_TEXT__SERIF_STYLE__OBTUSE_COVE",
    "LATIN_TEXT__SERIF_STYLE__SQUARE_COVE",
    "LATIN_TEXT__SERIF_STYLE__OBTUSE_SQUARE_COVE",
    "LATIN_TEXT__SERIF_STYLE__SQUARE",
    "LATIN_TEXT__SERIF_STYLE__THIN",
    "LATIN_TEXT__SERIF_STYLE__OVAL",
    "LATIN_TEXT__SERIF_STYLE__EXAGGERATED",
    "LATIN_TEXT__SERIF_STYLE__TRIANGLE",
    "LATIN_TEXT__SERIF_STYLE__NORMAL_SANS",
    "LATIN_TEXT__SERIF_STYLE__OBTUSE_SANS",
    "LATIN_TEXT__SERIF_STYLE__PERPENDICULAR_SANS",
    "LATIN_TEXT__WEIGHT__ANY",
    "LATIN_TEXT__WEIGHT__NO_FIT",
    "LATIN_TEXT__WEIGHT__VERY_LIGHT",
    "LATIN_TEXT__WEIGHT__LIGHT",
    "LATIN_TEXT__WEIGHT__THIN",
    "LATIN_TEXT__WEIGHT__BOOK",
    "LATIN_TEXT__WEIGHT__MEDIUM",
    "LATIN_TEXT__WEIGHT__DEMI",
    "LATIN_TEXT__WEIGHT__BOLD",
    "LATIN_TEXT__WEIGHT__HEAVY",
    "LATIN_TEXT__WEIGHT__BLACK",
    "LATIN_TEXT__WEIGHT__EXTRA_BLACK",
    "LATIN_TEXT__PROPORTION__ANY",
    "LATIN_TEXT__PROPORTION__NO_FIT",
    "LATIN_TEXT__PROPORTION__OLD_STYLE",
    "LATIN_TEXT__PROPORTION__MODERN",
    "LATIN_TEXT__PROPORTION__EVEN_WIDTH",
    "LATIN_TEXT__PROPORTION__EXTENDED",
    "LATIN_TEXT__PROPORTION__CONDENSED",
    "LATIN_TEXT__PROPORTION__VERY_EXTENDED",
    "LATIN_TEXT__PROPORTION__VERY_CONDENSED",
    "LATIN_TEXT__PROPORTION__MONOSPACED",
    "LATIN_TEXT__CONTRAST__ANY",
    "LATIN_TEXT__CONTRAST__NO_FIT",
    "LATIN_TEXT__CONTRAST__NONE",
    "LATIN_TEXT__CONTRAST__VERY_LOW",
    "LATIN_TEXT__CONTRAST__LOW",
    "LATIN_TEXT__CONTRAST__MEDIUM_LOW",
    "LATIN_TEXT__CONTRAST__MEDIUM",
    "LATIN_TEXT__CONTRAST__MEDIUM_HIGH",
    "LATIN_TEXT__CONTRAST__HIGH",
    "LATIN_TEXT__CONTRAST__VERY_HIGH",
    "LATIN_TEXT__STROKE_VARIATION__ANY",
    "LATIN_TEXT__STROKE_VARIATION__NO_FIT",
    "LATIN_TEXT__STROKE_VARIATION__NO_VARIATION",
    "LATIN_TEXT__STROKE_VARIATION__GRADUAL_DIAGONAL",
    "LATIN_TEXT__STROKE_VARIATION__GRADUAL_TRANSITIONAL",
    "LATIN_TEXT__STROKE_VARIATION__GRADUAL_VERTICAL",
    "LATIN_TEXT__STROKE_VARIATION__GRADUAL_HORIZONTAL",
    "LATIN_TEXT__STROKE_VARIATION__RAPID_VERTICAL",
    "LATIN_TEXT__STROKE_VARIATION__RAPID_HORIZONTAL",
    "LATIN_TEXT__STROKE_VARIATION__INSTANT_VERTICAL",
    "LATIN_TEXT__STROKE_VARIATION__INSTANT_HORIZONTAL",
    "LATIN_TEXT__ARM_STYLE__ANY",
    "LATIN_TEXT__ARM_STYLE__NO_FIT",
    "LATIN_TEXT__ARM_STYLE__STRAIGHT_ARMS_HORIZONTAL",
    "LATIN_TEXT__ARM_STYLE__STRAIGHT_ARMS_WEDGE",
    "LATIN_TEXT__ARM_STYLE__STRAIGHT_ARMS_VERTICAL",
    "LATIN_TEXT__ARM_STYLE__STRAIGHT_ARMS_SINGLE_SERIF",
    "LATIN_TEXT__ARM_STYLE__STRAIGHT_ARMS_DOUBLE_SERIF",
    "LATIN_TEXT__ARM_STYLE__NON_STRAIGHT_HORIZONTAL",
    "LATIN_TEXT__ARM_STYLE__NON_STRAIGHT_WEDGE",
    "LATIN_TEXT__ARM_STYLE__NON_STRAIGHT_VERTICAL",
    "LATIN_TEXT__ARM_STYLE__NON_STRAIGHT_SINGLE_SERIF",
    "LATIN_TEXT__ARM_STYLE__NON_STRAIGHT_DOUBLE_SERIF",
    "LATIN_TEXT__LETTERFORM__ANY",
    "LATIN_TEXT__LETTERFORM__NO_FIT",
    "LATIN_TEXT__LETTERFORM__NORMAL_CONTACT",
    "LATIN_TEXT__LETTERFORM__NORMAL_WEIGHTED",
    "LATIN_TEXT__LETTERFORM__NORMAL_BOXED",
    "LATIN_TEXT__LETTERFORM__NORMAL_FLATTENED",
    "LATIN_TEXT__LETTERFORM__NORMAL_ROUNDED",
    "LATIN_TEXT__LETTERFORM__NORMAL_OFF_CENTER",
    "LATIN_TEXT__LETTERFORM__NORMAL_SQUARE",
    "LATIN_TEXT__LETTERFORM__OBLIQUE_CONTACT",
    "LATIN_TEXT__LETTERFORM__OBLIQUE_WEIGHTED",
    "LATIN_TEXT__LETTERFORM__OBLIQUE_BOXED",
    "LATIN_TEXT__LETTERFORM__OBLIQUE_FLATTENED",
    "LATIN_TEXT__LETTERFORM__OBLIQUE_ROUNDED",
    "LATIN_TEXT__LETTERFORM__OBLIQUE_OFF_CENTER",
    "LATIN_TEXT__LETTERFORM__OBLIQUE_SQUARE",
    "LATIN_TEXT__MIDLINE__ANY",
    "LATIN_TEXT__MIDLINE__NO_FIT",
    "LATIN_TEXT__MIDLINE__STANDARD_TRIMMED",
    "LATIN_TEXT__MIDLINE__STANDARD_POINTED",
    "LATIN_TEXT__MIDLINE__STANDARD_SERIFED",
    "LATIN_TEXT__MIDLINE__HIGH_TRIMMED",
    "LATIN_TEXT__MIDLINE__HIGH_POINTED",
    "LATIN_TEXT__MIDLINE__HIGH_SERIFED",
    "LATIN_TEXT__MIDLINE__CONSTANT_TRIMMED",
    "LATIN_TEXT__MIDLINE__CONSTANT_POINTED",
    "LATIN_TEXT__MIDLINE__CONSTANT_SERIFED",
    "LATIN_TEXT__MIDLINE__LOW_TRIMMED",
    "LATIN_TEXT__MIDLINE__LOW_POINTED",
    "LATIN_TEXT__MIDLINE__LOW_SERIFED",
    "LATIN_TEXT__X_HEIGHT__ANY",
    "LATIN_TEXT__X_HEIGHT__NO_FIT",
    "LATIN_TEXT__X_HEIGHT__CONSTANT_SMALL",
    "LATIN_TEXT__X_HEIGHT__CONSTANT_STANDARD",
    "LATIN_TEXT__X_HEIGHT__CONSTANT_LARGE",
    "LATIN_TEXT__X_HEIGHT__DUCKING_SMALL",
    "LATIN_TEXT__X_HEIGHT__DUCKING_STANDARD",
    "LATIN_TEXT__X_HEIGHT__DUCKING_LARGE",
    "LATIN_HANDWRITTEN__FAMILY_KIND",
    "LATIN_HANDWRITTEN__TOOL_KIND",
    "LATIN_HANDWRITTEN__WEIGHT",
    "LATIN_HANDWRITTEN__SPACING",
    "LATIN_HANDWRITTEN__ASPECT_RATIO",
    "LATIN_HANDWRITTEN__CONTRAST",
    "LATIN_HANDWRITTEN__TOPOLOGY",
    "LATIN_HANDWRITTEN__FORM",
    "LATIN_HANDWRITTEN__FINIALS",
    "LATIN_HANDWRITTEN__X_ASCENT",
    "LATIN_HANDWRITTEN__TOOL_KIND__ANY",
    "LATIN_HANDWRITTEN__TOOL_KIND__NO_FIT",
    "LATIN_HANDWRITTEN__TOOL_KIND__FLAT_NIB",
    "LATIN_HANDWRITTEN__TOOL_KIND__PRESSURE_POINT",
    "LATIN_HANDWRITTEN__TOOL_KIND__ENGRAVED",
    "LATIN_HANDWRITTEN__TOOL_KIND__BALL_ROUND_CAP",
    "LATIN_HANDWRITTEN__TOOL_KIND__BRUSH",
    "LATIN_HANDWRITTEN__TOOL_KIND__ROUGH",
    "LATIN_HANDWRITTEN__TOOL_KIND__FELT_PEN_BRUSH_TIP",
    "LATIN_HANDWRITTEN__TOOL_KIND__WILD_BRUSH_DRIPS_A_LOT",
    "LATIN_HANDWRITTEN__WEIGHT__ANY",
    "LATIN_HANDWRITTEN__WEIGHT__NO_FIT",
    "LATIN_HANDWRITTEN__WEIGHT__VERY_LIGHT",
    "LATIN_HANDWRITTEN__WEIGHT__LIGHT",
    "LATIN_HANDWRITTEN__WEIGHT__THIN",
    "LATIN_HANDWRITTEN__WEIGHT__BOOK",
    "LATIN_HANDWRITTEN__WEIGHT__MEDIUM",
    "LATIN_HANDWRITTEN__WEIGHT__DEMI",
    "LATIN_HANDWRITTEN__WEIGHT__BOLD",
    "LATIN_HANDWRITTEN__WEIGHT__HEAVY",
    "LATIN_HANDWRITTEN__WEIGHT__BLACK",
    "LATIN_HANDWRITTEN__WEIGHT__EXTRA_BLACK_NORD",
    "LATIN_HANDWRITTEN__SPACING__ANY",
    "LATIN_HANDWRITTEN__SPACING__NO_FIT",
    "LATIN_HANDWRITTEN__SPACING__PROPORTIONAL_SPACED",
    "LATIN_HANDWRITTEN__SPACING__MONOSPACED",
    "LATIN_HANDWRITTEN__ASPECT_RATIO__ANY",
    "LATIN_HANDWRITTEN__ASPECT_RATIO__NO_FIT",
    "LATIN_HANDWRITTEN__ASPECT_RATIO__VERY_CONDENSED",
    "LATIN_HANDWRITTEN__ASPECT_RATIO__CONDENSED",
    "LATIN_HANDWRITTEN__ASPECT_RATIO__NORMAL",
    "LATIN_HANDWRITTEN__ASPECT_RATIO__EXPANDED",
    "LATIN_HANDWRITTEN__ASPECT_RATIO__VERY_EXPANDED",
    "LATIN_HANDWRITTEN__CONTRAST__ANY",
    "LATIN_HANDWRITTEN__CONTRAST__NO_FIT",
    "LATIN_HANDWRITTEN__CONTRAST__NONE",
    "LATIN_HANDWRITTEN__CONTRAST__VERY_LOW",
    "LATIN_HANDWRITTEN__CONTRAST__LOW",
    "LATIN_HANDWRITTEN__CONTRAST__MEDIUM_LOW",
    "LATIN_HANDWRITTEN__CONTRAST__MEDIUM",
    "LATIN_HANDWRITTEN__CONTRAST__MEDIUM_HIGH",
    "LATIN_HANDWRITTEN__CONTRAST__HIGH",
    "LATIN_HANDWRITTEN__CONTRAST__VERY_HIGH",
    "LATIN_HANDWRITTEN__TOPOLOGY__ANY",
    "LATIN_HANDWRITTEN__TOPOLOGY__NO_FIT",
    "LATIN_HANDWRITTEN__TOPOLOGY__ROMAN_DISCONNECTED",
    "LATIN_HANDWRITTEN__TOPOLOGY__ROMAN_TRAILING",
    "LATIN_HANDWRITTEN__TOPOLOGY__ROMAN_CONNECTED",
    "LATIN_HANDWRITTEN__TOPOLOGY__CURSIVE_DISCONNECTED",
    "LATIN_HANDWRITTEN__TOPOLOGY__CURSIVE_TRAILING",
    "LATIN_HANDWRITTEN__TOPOLOGY__CURSIVE_CONNECTED",
    "LATIN_HANDWRITTEN__TOPOLOGY__BLACKLETTER_DISCONNECTED",
    "LATIN_HANDWRITTEN__TOPOLOGY__BLACKLETTER_TRAILING",
    "LATIN_HANDWRITTEN__TOPOLOGY__BLACKLETTER_CONNECTED",
    "LATIN_HANDWRITTEN__FORM__ANY",
    "LATIN_HANDWRITTEN__FORM__NO_FIT",
    "LATIN_HANDWRITTEN__FORM__UPRIGHT_NO_WRAPPING",
    "LATIN_HANDWRITTEN__FORM__UPRIGHT_SOME_WRAPPING",
    "LATIN_HANDWRITTEN__FORM__UPRIGHT_MORE_WRAPPING",
    "LATIN_HANDWRITTEN__FORM__UPRIGHT_EXTREME_WRAPPING",
    "LATIN_HANDWRITTEN__FORM__OBLIQUE_NO_WRAPPING",
    "LATIN_HANDWRITTEN__FORM__OBLIQUE_SOME_WRAPPING",
    "LATIN_HANDWRITTEN__FORM__OBLIQUE_MORE_WRAPPING",
    "LATIN_HANDWRITTEN__FORM__OBLIQUE_EXTREME_WRAPPING",
    "LATIN_HANDWRITTEN__FORM__EXAGGERATED_NO_WRAPPING",
    "LATIN_HANDWRITTEN__FORM__EXAGGERATED_SOME_WRAPPING",
    "LATIN_HANDWRITTEN__FORM__EXAGGERATED_MORE_WRAPPING",
    "LATIN_HANDWRITTEN__FORM__EXAGGERATED_EXTREME_WRAPPING",
    "LATIN_HANDWRITTEN__FINIALS__ANY",
    "LATIN_HANDWRITTEN__FINIALS__NO_FIT",
    "LATIN_HANDWRITTEN__FINIALS__NONE_NO_LOOPS",
    "LATIN_HANDWRITTEN__FINIALS__NONE_CLOSED_LOOPS",
    "LATIN_HANDWRITTEN__FINIALS__NONE_OPEN_LOOPS",
    "LATIN_HANDWRITTEN__FINIALS__SHARP_NO_LOOPS",
    "LATIN_HANDWRITTEN__FINIALS__SHARP_CLOSED_LOOPS",
    "LATIN_HANDWRITTEN__FINIALS__SHARP_OPEN_LOOPS",
    "LATIN_HANDWRITTEN__FINIALS__TAPERED_NO_LOOPS",
    "LATIN_HANDWRITTEN__FINIALS__TAPERED_CLOSED_LOOPS",
    "LATIN_HANDWRITTEN__FINIALS__TAPERED_OPEN_LOOPS",
    "LATIN_HANDWRITTEN__X_ASCENT__ANY",
    "LATIN_HANDWRITTEN__X_ASCENT__NO_FIT",
    "LATIN_HANDWRITTEN__X_ASCENT__VERY_LOW",
    "LATIN_HANDWRITTEN__X_ASCENT__LOW",
    "LATIN_HANDWRITTEN__X_ASCENT__MEDIUM",
    "LATIN_HANDWRITTEN__X_ASCENT__HIGH",
    "LATIN_HANDWRITTEN__X_ASCENT__VERY_HIGH",
    "LATIN_DECORATIVE__FAMILY_KIND",
    "LATIN_DECORATIVE__CLASS",
    "LATIN_DECORATIVE__WEIGHT",
    "LATIN_DECORATIVE__ASPECT",
    "LATIN_DECORATIVE__CONTRAST",
    "LATIN_DECORATIVE__SERIF_VARIANT",
    "LATIN_DECORATIVE__TREATMENT",
    "LATIN_DECORATIVE__LINING",
    "LATIN_DECORATIVE__TOPOLOGY",
    "LATIN_DECORATIVE__RANGE_OF_CHARACTERS",
    "LATIN_DECORATIVE__CLASS__ANY",
    "LATIN_DECORATIVE__CLASS__NO_FIT",
    "LATIN_DECORATIVE__CLASS__DERIVATIVE",
    "LATIN_DECORATIVE__CLASS__NON_STANDARD_TOPOLOGY",
    "LATIN_DECORATIVE__CLASS__NON_STANDARD_ELEMENTS",
    "LATIN_DECORATIVE__CLASS__NON_STANDARD_ASPECT",
    "LATIN_DECORATIVE__CLASS__INITIALS",
    "LATIN_DECORATIVE__CLASS__CARTOON",
    "LATIN_DECORATIVE__CLASS__PICTURE_STEMS",
    "LATIN_DECORATIVE__CLASS__ORNAMENTED",
    "LATIN_DECORATIVE__CLASS__TEXT_AND_BACKGROUND",
    "LATIN_DECORATIVE__CLASS__COLLAGE",
    "LATIN_DECORATIVE__CLASS__MONTAGE",
    "LATIN_DECORATIVE__WEIGHT__ANY",
    "LATIN_DECORATIVE__WEIGHT__NO_FIT",
    "LATIN_DECORATIVE__WEIGHT__VERY_LIGHT",
    "LATIN_DECORATIVE__WEIGHT__LIGHT",
    "LATIN_DECORATIVE__WEIGHT__THIN",
    "LATIN_DECORATIVE__WEIGHT__BOOK",
    "LATIN_DECORATIVE__WEIGHT__MEDIUM",
    "LATIN_DECORATIVE__WEIGHT__DEMI",
    "LATIN_DECORATIVE__WEIGHT__BOLD",
    "LATIN_DECORATIVE__WEIGHT__HEAVY",
    "LATIN_DECORATIVE__WEIGHT__BLACK",
    "LATIN_DECORATIVE__WEIGHT__EXTRA_BLACK",
    "LATIN_DECORATIVE__ASPECT__ANY",
    "LATIN_DECORATIVE__ASPECT__NO_FIT",
    "LATIN_DECORATIVE__ASPECT__SUPER_CONDENSED",
    "LATIN_DECORATIVE__ASPECT__VERY_CONDENSED",
    "LATIN_DECORATIVE__ASPECT__CONDENSED",
    "LATIN_DECORATIVE__ASPECT__NORMAL",
    "LATIN_DECORATIVE__ASPECT__EXTENDED",
    "LATIN_DECORATIVE__ASPECT__VERY_EXTENDED",
    "LATIN_DECORATIVE__ASPECT__SUPER_EXTENDED",
    "LATIN_DECORATIVE__ASPECT__MONOSPACED",
    "LATIN_DECORATIVE__CONTRAST__ANY",
    "LATIN_DECORATIVE__CONTRAST__NO_FIT",
    "LATIN_DECORATIVE__CONTRAST__NONE",
    "LATIN_DECORATIVE__CONTRAST__VERY_LOW",
    "LATIN_DECORATIVE__CONTRAST__LOW",
    "LATIN_DECORATIVE__CONTRAST__MEDIUM_LOW",
    "LATIN_DECORATIVE__CONTRAST__MEDIUM",
    "LATIN_DECORATIVE__CONTRAST__MEDIUM_HIGH",
    "LATIN_DECORATIVE__CONTRAST__HIGH",
    "LATIN_DECORATIVE__CONTRAST__VERY_HIGH",
    "LATIN_DECORATIVE__CONTRAST__HORIZONTAL_LOW",
    "LATIN_DECORATIVE__CONTRAST__HORIZONTAL_MEDIUM",
    "LATIN_DECORATIVE__CONTRAST__HORIZONTAL_HIGH",
    "LATIN_DECORATIVE__CONTRAST__BROKEN",
    "LATIN_DECORATIVE__SERIF_VARIANT__ANY",
    "LATIN_DECORATIVE__SERIF_VARIANT__NO_FIT",
    "LATIN_DECORATIVE__SERIF_VARIANT__COVE",
    "LATIN_DECORATIVE__SERIF_VARIANT__OBTUSE_COVE",
    "LATIN_DECORATIVE__SERIF_VARIANT__SQUARE_COVE",
    "LATIN_DECORATIVE__SERIF_VARIANT__OBTUSE_SQUARE_COVE",
    "LATIN_DECORATIVE__SERIF_VARIANT__SQUARE",
    "LATIN_DECORATIVE__SERIF_VARIANT__THIN",
    "LATIN_DECORATIVE__SERIF_VARIANT__OVAL",
    "LATIN_DECORATIVE__SERIF_VARIANT__EXAGGERATED",
    "LATIN_DECORATIVE__SERIF_VARIANT__TRIANGLE",
    "LATIN_DECORATIVE__SERIF_VARIANT__NORMAL_SANS",
    "LATIN_DECORATIVE__SERIF_VARIANT__OBTUSE_SANS",
    "LATIN_DECORATIVE__SERIF_VARIANT__PERPENDICULAR_SANS",
    "LATIN_DECORATIVE__SERIF_VARIANT__FLARED",
    "LATIN_DECORATIVE__SERIF_VARIANT__ROUNDED",
    "LATIN_DECORATIVE__SERIF_VARIANT__SCRIPT",
    "LATIN_DECORATIVE__TREATMENT__ANY",
    "LATIN_DECORATIVE__TREATMENT__NO_FIT",
    "LATIN_DECORATIVE__TREATMENT__NONE_STANDARD_SOLID_FILL",
    "LATIN_DECORATIVE__TREATMENT__WHITE_NO_FILL",
    "LATIN_DECORATIVE__TREATMENT__PATTERNED_FILL",
    "LATIN_DECORATIVE__TREATMENT__COMPLEX_FILL",
    "LATIN_DECORATIVE__TREATMENT__SHAPED_FILL",
    "LATIN_DECORATIVE__TREATMENT__DRAWN_DISTRESSED",
    "LATIN_DECORATIVE__LINING__ANY",
    "LATIN_DECORATIVE__LINING__NO_FIT",
    "LATIN_DECORATIVE__LINING__NONE",
    "LATIN_DECORATIVE__LINING__INLINE",
    "LATIN_DECORATIVE__LINING__OUTLINE",
    "LATIN_DECORATIVE__LINING__ENGRAVED_MULTIPLE_LINES",
    "LATIN_DECORATIVE__LINING__SHADOW",
    "LATIN_DECORATIVE__LINING__RELIEF",
    "LATIN_DECORATIVE__LINING__BACKDROP",
    "LATIN_DECORATIVE__TOPOLOGY__ANY",
    "LATIN_DECORATIVE__TOPOLOGY__NO_FIT",
    "LATIN_DECORATIVE__TOPOLOGY__STANDARD",
    "LATIN_DECORATIVE__TOPOLOGY__SQUARE",
    "LATIN_DECORATIVE__TOPOLOGY__MULTIPLE_SEGMENT",
    "LATIN_DECORATIVE__TOPOLOGY__DECO_E_M_S_WACO_MIDLINES",
    "LATIN_DECORATIVE__TOPOLOGY__UNEVEN_WEIGHTING",
    "LATIN_DECORATIVE__TOPOLOGY__DIVERSE_ARMS",
    "LATIN_DECORATIVE__TOPOLOGY__DIVERSE_FORMS",
    "LATIN_DECORATIVE__TOPOLOGY__LOMBARDIC_FORMS",
    "LATIN_DECORATIVE__TOPOLOGY__UPPER_CASE_IN_LOWER_CASE",
    "LATIN_DECORATIVE__TOPOLOGY__IMPLIED_TOPOLOGY",
    "LATIN_DECORATIVE__TOPOLOGY__HORSESHOE_E_AND_A",
    "LATIN_DECORATIVE__TOPOLOGY__CURSIVE",
    "LATIN_DECORATIVE__TOPOLOGY__BLACKLETTER",
    "LATIN_DECORATIVE__TOPOLOGY__SWASH_VARIANCE",
    "LATIN_DECORATIVE__RANGE_OF_CHARACTERS__ANY",
    "LATIN_DECORATIVE__RANGE_OF_CHARACTERS__NO_FIT",
    "LATIN_DECORATIVE__RANGE_OF_CHARACTERS__EXTENDED_COLLECTION",
    "LATIN_DECORATIVE__RANGE_OF_CHARACTERS__LITTERALS",
    "LATIN_DECORATIVE__RANGE_OF_CHARACTERS__NO_LOWER_CASE",
    "LATIN_DECORATIVE__RANGE_OF_CHARACTERS__SMALL_CAPS",
    "LATIN_SYMBOL__FAMILY_KIND",
    "LATIN_SYMBOL__KIND",
    "LATIN_SYMBOL__WEIGHT",
    "LATIN_SYMBOL__SPACING",
    "LATIN_SYMBOL__ASPECT_RATIO_CONTRAST",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_94",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_119",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_157",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_163",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_211",
    "LATIN_SYMBOL__KIND__ANY",
    "LATIN_SYMBOL__KIND__NO_FIT",
    "LATIN_SYMBOL__KIND__MONTAGES",
    "LATIN_SYMBOL__KIND__PICTURES",
    "LATIN_SYMBOL__KIND__SHAPES",
    "LATIN_SYMBOL__KIND__SCIENTIFIC",
    "LATIN_SYMBOL__KIND__MUSIC",
    "LATIN_SYMBOL__KIND__EXPERT",
    "LATIN_SYMBOL__KIND__PATTERNS",
    "LATIN_SYMBOL__KIND__BOARDERS",
    "LATIN_SYMBOL__KIND__ICONS",
    "LATIN_SYMBOL__KIND__LOGOS",
    "LATIN_SYMBOL__KIND__INDUSTRY_SPECIFIC",
    "LATIN_SYMBOL__WEIGHT__NO_FIT",
    "LATIN_SYMBOL__SPACING__ANY",
    "LATIN_SYMBOL__SPACING__NO_FIT",
    "LATIN_SYMBOL__SPACING__PROPORTIONAL_SPACED",
    "LATIN_SYMBOL__SPACING__MONOSPACED",
    "LATIN_SYMBOL__ASPECT_RATIO_CONTRAST__NO_FIT",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__ANY",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__NO_FIT",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__NO_WIDTH",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__EXCEPTIONALLY_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__SUPER_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__VERY_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__NORMAL",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__NARROW",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_94__VERY_NARROW",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__ANY",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__NO_FIT",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__NO_WIDTH",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__EXCEPTIONALLY_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__SUPER_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__VERY_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__NORMAL",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__NARROW",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_119__VERY_NARROW",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__ANY",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__NO_FIT",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__NO_WIDTH",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__EXCEPTIONALLY_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__SUPER_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__VERY_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__NORMAL",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__NARROW",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_157__VERY_NARROW",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__ANY",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__NO_FIT",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__NO_WIDTH",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__EXCEPTIONALLY_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__SUPER_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__VERY_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__NORMAL",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__NARROW",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_163__VERY_NARROW",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__ANY",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__NO_FIT",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__NO_WIDTH",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__EXCEPTIONALLY_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__SUPER_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__VERY_WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__WIDE",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__NORMAL",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__NARROW",
    "LATIN_SYMBOL__ASPECT_RATIO_CHAR_211__VERY_NARROW",
    "FIELD__FAMILY_KIND",
]
